services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: escola
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "7777:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - default

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - default

  api_turma:
    build:
      context: ./api_turma
      dockerfile: Dockerfile
    container_name: api_turma
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql_db
      - redis
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB_NAME: escola
      REDIS_HOST: redis
    networks:
      - default

  api_presenca:
    build:
      context: ./api_presenca
      dockerfile: Dockerfile
    container_name: api_presenca
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
      - redis
    environment:
      DB_HOST: mysql_db
      DB_PORT: 3306
      DB_USER: root
      DB_PASS: root
      DB_NAME: escola
      REDIS_HOST: redis
    networks:
      - default

  api_chamada:
    build:
      context: ./api_chamada
      dockerfile: Dockerfile
    container_name: api_chamada
    restart: always
    ports:
      - "4000:4000"
    depends_on:
      - api_turma
      - api_presenca
    environment:
      API_TURMA: http://api_turma:3000
      API_PRESENCA: http://api_presenca:5000
      REDIS_HOST: redis
    networks:
      - default

volumes:
  mysql_data:

networks:
  default: {}
